version: "2"
services:
  web:
    build: .
    ports:
    - "3001:3000"
    #- "3000:3000"
    depends_on:
    - mongo
    restart: always
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      #- /Users/marcosgamazo/mongo-persistent:/data/db
      - /home/meteoros/mongodb:/data/db
    command: [--auth] 